version: '3.7'

# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
services:
  web:
    build:
      context: ./app
    # command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn nedo3.wsgi:application --bind 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 nedo3.asgi:application
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/static
    tty: true
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      # - 80:80
      - $HTTP_PORT:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
