# pull official base image
FROM python:3.8.3-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# ARG DEBUG
# ENV DEBUG $DEBUG
# ARG SECRET_KEY
# ENV SECRET_KEY $SECRET_KEY
# ARG DJANGO_ALLOWED_HOSTS
# ENV DJANGO_ALLOWED_HOSTS $DJANGO_ALLOWED_HOSTS
# ARG ADMIN_PASSWORD

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .

# copy project
COPY . .

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

# RUN python ./manage.py migrate
# # RUN python ./manage.py createsuperuser --username= --email=<email>
# RUN python ./manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'goran.topic@aist.go.jp', '$ADMIN_PASSWORD')"
# RUN python ./manage.py collectstatic
