# Generated by Django 3.1.4 on 2020-12-21 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('S', 'Started'), ('F', 'Finished'), ('E', 'Error')], default='S', max_length=1)),
                ('viewed', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=30)),
                ('txt', models.TextField()),
                ('ann', models.TextField(blank=True, null=True)),
                ('visual_conf', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'state'], name='webapp_job_user_id_f27b03_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['started_at'], name='webapp_job_started_a2412a_idx'),
        ),
    ]
