version: '3.7'

# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
services:
  web:
    build:
      context: ./app
    # command: python manage.py runserver 0.0.0.0:8000
    # command: hypercorn --bind 0.0.0.0:8001 sample_worker.asgi:app
    command: gunicorn sample_worker.wsgi:app --bind 0.0.0.0:$PORT
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/static
    tty: true
    ports:
      - 8001:8001
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
